# Generated by Django 6.0.3 on 2026-03-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='temparature',
            new_name='temperature',
        ),
    ]
