# Generated by Django 6.0.3 on 2026-03-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_temparature_weatherdata_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='media/abcd'),
        ),
    ]
