# Generated by Django 6.0.3 on 2026-03-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
